### PR TITLE
asterisk-14.x: New version slot

### PR DESCRIPTION
**Pull request by DL7RAY**
This is a new version slot of asterisk (v14.2.1).. It compiles very well with arm7 gcc cross compiler (v6.3.0)..

### CODE REVIEW

**Comment by zyxmon** [comment]
Does it work?
There are some openwrt specific files in you PR. What are the reasons to include them?

**Comment by ryzhovau** [comment]
The same as [here](https://github.com/Entware-ng/entware-telephony/pull/2#issuecomment-279199498).

**Comment by ryzhovau** [comment]
Will keep it open for awhile. Upstream doesn't seems to be alive.

**Comment by ryzhovau** [comment]
Upstream is alive, so it's better to send this PR to them.

**Pull request closed without merging**
